---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: anarchy-operator
  namespace: anarchy-operator
---
apiVersion: v1
kind: Service
metadata:
  name: anarchy-operator
  namespace: anarchy-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anarchy-operator
  namespace: anarchy-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anarchy-runner-default
  namespace: anarchy-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anarchy-operator
  namespace: anarchy-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anarchy-operator
  namespace: anarchy-operator
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: anarchy-operator
  namespace: anarchy-k8s-config
---
apiVersion: v1
kind: Service
metadata:
  name: anarchy-operator
  namespace: anarchy-k8s-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anarchy-operator
  namespace: anarchy-k8s-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anarchy-runner-default
  namespace: anarchy-k8s-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anarchy-operator
  namespace: anarchy-k8s-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anarchy-operator
  namespace: anarchy-k8s-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-anarchy-k8s-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: poolboy:anarchy-operator:anarchy-runner-default
