---
- name: Setup Babylon OpenShift GitOps
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # Override deploy key variable with extra vars
    babylon_repo_url: https://github.com/redhat-cop/babylon.git
    babylon_repo_version: master
    babylon_private_repo_url: ''
    babylon_private_repo_version: master
    babylon_private_deploy_key: ''

    k8s_config:
      run_interval: 1h

    k8s_config_sources:
    # Load private config source with highest priority if deploy key is available
    - name: babylon-private
      base_path: openshift/config
      git:
        accept_hostkey: true
        repo: "{{ babylon_private_repo_url }}"
        key_file: "{{ babylon_private_deploy_key }}"
        version: "{{ babylon_private_repo_version }}"
      when: babylon_private_deploy_key != ''

    # Local config, should be openshift/config in babylon repository
    - name: local
      base_path: "{{ playbook_dir }}"

  pre_tasks:
  - name: Check value of k8s_config_environment_level
    fail:
      msg: k8s_config_environment_level must be set to 'dev', 'test', or 'prod'
    when: >-
      k8s_config_environment_level|default('') not in ['dev', 'test', 'prod']

  - name: Get cluster version
    k8s_info:
      api_version: config.openshift.io/v1
      kind: ClusterVersion
      name: version
    register: _k8s_info_cluster_version

  - name: Get OpenShift API server information
    k8s_info:
      api_version: config.openshift.io/v1
      kind: ClusterOperator
      name: openshift-apiserver
    register: _k8s_info_cluster_operator_openshift_apiserver

  - name: Get cluster ingress configuration
    k8s_info:
      api_version: config.openshift.io/v1
      kind: Ingress
      name: cluster
    register: _k8s_info_cluster_ingress

  - name: Set k8s_cluster_info with set_k8s_cluster_info and discovered information
    set_fact:
      k8s_cluster_info:
        cluster_domain: >-
          {{ _k8s_info_cluster_ingress.resources[0].spec.domain
           | regex_replace('^apps\.', '')
           | regex_replace('cluster-(.*)\.\1', '\1')
          }}
        cluster_id: >-
          {{ _k8s_info_cluster_version.resources[0].spec.clusterID }}
        cluster_ingress_domain: >-
          {{ _k8s_info_cluster_ingress.resources[0].spec.domain }}
        env_level: >-
          {{ k8s_config_environment_level }}

  - name: Set openshift_api_version, openshift_api_minor_version, and openshift_version_channel
    set_fact:
      openshift_api_minor_version: >-
        {{ _k8s_info_cluster_operator_openshift_apiserver.resources[0]
         | json_query("status.versions[?name=='openshift-apiserver']|[0].version")
         | regex_replace("\.\d+$", "")
        }}
      openshift_api_version: >-
        {{ _k8s_info_cluster_operator_openshift_apiserver.resources[0]
         | json_query("status.versions[?name=='openshift-apiserver']|[0].version")
        }}
      openshift_version_channel: >-
        {{ _k8s_info_cluster_version.resources[0].spec.channel }}

  roles:
  - role: k8s_config
