---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-cluster-admin
  annotations:
    description: >-
      Cluster-wide admin access for Babylon resources.
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ .Values.catalog.apiGroup }}
  resources:
  - catalogitems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - {{ .Values.anarchy.apiGroup }}
  resources:
  - anarchyactions
  - anarchycommunes
  - anarchygovernors
  - anarchyruns
  - anarchyrunners
  - anarchysubjects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - {{ .Values.resourceBroker.apiGroup }}
  resources:
  - resourceclaims
  - resourcehandles
  - resourcepools
  - resourceproviders
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.catalog.apiGroup }}
  resources:
  - workshops
  - workshopprovisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-cluster-reader
  annotations:
    description: >-
      Cluster-wide read access for Babylon resources.
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
    {{- include "babylon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ .Values.catalog.apiGroup }}
  resources:
  - catalogitems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - {{ .Values.anarchy.apiGroup }}
  resources:
  - anarchyactions
  - anarchycommunes
  - anarchygovernors
  - anarchyruns
  - anarchyrunners
  - anarchysubjects
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-user-catalog-access
  annotations:
    description: >-
      Access to Babylon catalog resources.
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    {{- include "babylon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ .Values.catalog.apiGroup }}
  resources:
  - catalogitems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - template.openshift.io
  resources:
  - templates
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-user-service-access
  annotations:
    description: >-
      Access to manage Babylon services.
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    {{- include "babylon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ .Values.resourceBroker.apiGroup }}
  resources:
  - resourceclaims
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.catalog.apiGroup }}
  resources:
  - workshops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon-workshop-admin
  annotations:
    description: >-
      Access to manage workshops and provisions for workshops.
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    {{- include "babylon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ .Values.catalog.apiGroup }}
  resources:
  - workshops
  - workshopprovisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon:resource-broker:anarchy-access
  annotations:
    description: >-
      This role is used to allow the resource broker to manage anarchy resources.
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
rules:
# ConfigMap access to create user configmaps
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
  - update
- apiGroups:
  - {{ .Values.anarchy.apiGroup }}
  resources:
  - anarchysubjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: babylon:{{ .Values.resourceBroker.namespace }}:anarchy-access
  annotations:
    description: >-
      This rolebinding allows the resource broker to manage anarchy resources.
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: babylon:resource-broker:anarchy-access
subjects:
- kind: ServiceAccount
  name: resource-broker
  namespace: {{ .Values.resourceBroker.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon:anarchy:resource-broker-access
  annotations:
    description: >-
      This cluster role is used to allow anarchy to manage ResourceClaims and ResourceHandles.
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ .Values.resourceBroker.apiGroup }}
  resources:
  - resourceclaims
  - resourcehandles
  verbs:
  - delete
  - get
  - list
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: babylon:anarchy:catalog-access
  annotations:
    description: >-
      This cluster role is used to allow anarchy to access catalog items and secrets.
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ .Values.catalog.apiGroup }}
  resources:
  - catalogitems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - template.openshift.io
  resources:
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
