{{- $serviceAccessManager := .Values.serviceAccessManager }}
{{- if and $serviceAccessManager.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: babylon-service-access-manager
  namespace: {{ $serviceAccessManager.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-access-manager
{{- end }}
