{{- if (.Values.ratings).deploy -}}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ .Values.ratings.db.secretName }}
  namespace: {{ .Values.ratings.namespace.name | default (printf "%s-ratings" .Release.Namespace) }}
spec:
  data:
    hostname:
      secret: {{ .Values.ratings.db.bitwardenSecret }}
      key: hostname
    hostname_ro:
      secret: {{ .Values.ratings.db.bitwardenSecret }}
      key: hostname_ro
    username:
      secret: {{ .Values.ratings.db.bitwardenSecret }}
      key: username
    password:
      secret: {{ .Values.ratings.db.bitwardenSecret }}
      key: password
    name:
      secret: {{ .Values.ratings.db.bitwardenSecret }}
      key: name
    port:
      secret: {{ .Values.ratings.db.bitwardenSecret }}
      key: port
{{- end }}
