{{- $catalogManager := .Values.catalogManager }}
{{- if $catalogManager.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: babylon-catalog-manager
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalog-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: babylon-catalog-manager
subjects:
- kind: ServiceAccount
  name: babylon-catalog-manager
  namespace: {{ $catalogManager.namespace.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: babylon-catalog-manager:admin
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalog-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: babylon-catalog-manager
  namespace: {{ $catalogManager.namespace.name }}
{{- end }}
