{{- $catalogManager := .Values.catalogManager }}
{{- if and $catalogManager.deploy $catalogManager.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "babylon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: catalog-manager
  name: {{ $catalogManager.namespace.name }}
{{- end }}
