{{- $catalogManager := .Values.catalogManager }}
{{- if $catalogManager.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: babylon-catalog-manager
  namespace: {{ $catalogManager.namespace.name }}
  labels:
    {{- include "babylon.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalog-manager
{{- end }}
