---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceaccesses.babylon.gpte.redhat.com
spec:
  conversion:
    strategy: None
  group: babylon.gpte.redhat.com
  names:
    kind: ServiceAccess
    listKind: ServiceAccessList
    plural: serviceaccesses
    singular: serviceaccess
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: >-
          Reports user access to a service such as a Workshop or ResourceClaim.
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                maxLength: 63
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-._]*[a-z0-9A-Z])?$
                type: string
            type: object
          spec:
            description: Specification of ServiceAccess.
            type: object
            properties:
              kind:
                description:
                  Kind of object for which the user has access.
                  Either "ResourceClaim" or "Workshop".
                type: string
                enum:
                - ResourceClaim
                - Workshop
              name:
                description: >-
                  Name of the object.
                type: string
              namespace:
                description: >-
                  Namespace of the object.
                type: string
              serviceAccessConfigName:
                description: >-
                  Name of ServiceAccessConfig which controls the ServiceAccess record.
                type: string
          status:
            description: Status of ServiceAccess
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              diffBase:
                description: Kopf diffbase
                type: string
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
