---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceaccessconfigs.babylon.gpte.redhat.com
spec:
  conversion:
    strategy: None
  group: babylon.gpte.redhat.com
  names:
    kind: ServiceAccessConfig
    listKind: ServiceAccessConfigList
    plural: serviceaccessconfigs
    singular: serviceaccessconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: >-
          Configure access to a service such as a Workshop or ResourceClaim.
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                maxLength: 63
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-._]*[a-z0-9A-Z])?$
                type: string
            type: object
          spec:
            description: Specification of ServiceAccessConfig.
            type: object
            properties:
              kind:
                description:
                  Kind of object for access configuration.
                  Either "ResourceClaim" or "Workshop".
                type: string
                enum:
                - ResourceClaim
                - Workshop
              name:
                description: >-
                  Name of object for which to configure access.
                type: string
              users:
                description: >-
                  List of users to grant access to the service.
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: >-
                        User name.
                      type: string
          status:
            description: Status of ServiceAccessConfig
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              diffBase:
                description: Kopf diffbase
                type: string
              kopf:
                description: Kopf status storage
                type: object
                x-kubernetes-preserve-unknown-fields: true
              serviceAccesses:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
