---
# This Ansible Playbook show how to add an Anarchy Subject through a Poolboy
# ResourceHandle and ResourceClaim while setting an explicit GUID.
- name: Babylon Integration
  hosts: localhost
  vars:
    account: rhte
    catalog_item: BABYLON_OCP_CLIENTVM 
    catalog_stage: dev
    catalog_item_vars:
      osrelease: 3.11.98
    cloudforms_username: "{{ lookup('env', 'USERNAME') }}"
    guid: abcde

    catalog_item_name: "{{ account | replace('_', '-') }}.{{ catalog_item | lower | regex_replace('_', '-') }}.{{ catalog_stage }}"
    openshift_username: "{{ cloudforms_username }}"
    user_namespace: user-{{ openshift_username | replace('.', '-') }}

    poolboy_resource_definition:
      provider:
        apiVersion: poolboy.gpte.redhat.com/v1
        kind: ResourceProvider
        name: babylon
        namespace: poolboy
      template:
        apiVersion: anarchy.gpte.redhat.com/v1
        kind: AnarchySubject
        metadata:
          annotations:
            poolboy.gpte.redhat.com/resource-provider-name: babylon
            poolboy.gpte.redhat.com/resource-provider-namespace: poolboy
          generateName: "{{ catalog_item_name }}-"
        spec:
          desiredState: started
          governor: "{{ catalog_item_name }}"
          vars:
            job_vars: "{{ vars.catalog_item_vars | combine({'guid': guid}) }}"

  tasks:
  - name: Create namespace for {{ openshift_username }}
    k8s:
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          annotations:
            openshift.io/description: User Namespace for {{ openshift_username }}
            openshift.io/display-name: "{{ user_namespace }}"
            openshift.io/requester: "{{ openshift_username }}"
          name: "{{ user_namespace }}"

  - name: Create resource handle for GUID {{ guid }}
    k8s:
      definition:
        apiVersion: poolboy.gpte.redhat.com/v1
        kind: ResourceHandle
        metadata:
          labels:
            poolboy.gpte.redhat.com/resource-pool-name: babylon-explicit-guid
          name: guid-{{ guid }}
          namespace: poolboy
        spec:
          resources:
          - "{{ poolboy_resource_definition }}"

  - name: Create resource handle for GUID {{ guid }}
    k8s:
      definition:
        apiVersion: poolboy.gpte.redhat.com/v1
        kind: ResourceClaim
        metadata:
          labels:
            poolboy.gpte.redhat.com/resource-pool-name: babylon-explicit-guid
          name: "{{ catalog_item_name }}-{{ guid }}"
          namespace: "{{ user_namespace }}"
        spec:
          resources:
          - "{{ poolboy_resource_definition }}"
